371team4/371Team4

test/e2e/specs/test.js
test/e2e/specs/web_app.js

* Add basic e2e test cases for Nightwatch
* invest more into testing
* tests will serve as reference for getting started writing future tests

Add sample test cases

---

src/components/AddSlideTest.vue
src/router/index.js
src/services/firebase.conf.js
src/store/modules/slide/index.js
src/store/mutation-types.js

commit create-newslide-action

---

Jenkinsfile

I'm making Jenkins actually run commands in the pipeline

Insert npm commands

---

config/index.js

Enforce chrome browser in development environment 
* Enforce chrome browser in development environment 
* Use polling to force hot reloading on mac os systems 
All developers need to develop against the same browser

Enforce chrome browser in development environment 

---

Jenkinsfile

Add check for empty CHANGE_TARGET

---

Jenkinsfile

Make check for branch name a nested if condition

---

Jenkinsfile

[TO MASTER] Insert npm commands to Jenkinsfile

---

Jenkinsfile

Remove quotes

---

Jenkinsfile
test/e2e/nightwatch.conf.js
test/e2e/specs/test.js

Fixing weird issues

---

src/App.vue
src/router/index.js

Refactor router to redirect to Slides page 
* Refactor router to redirect to Slides page 
* Use navigation tabs that have a name and an icon
* Remove side effects of authentication logic

Refactor router to redirect to Slides page 

---

test/unit/specs/store/Upload.spec.js

Add fix for UploadSingleFile testcase issue #42
Please see issue #42 
Please see issue #42

Add fix for UploadSingleFile testcase issue #42

---

npm-shrinkwrap.json
package.json

Upgrade vuetify and remove precommit from dependencies 
Upgrade vuetify and remove precommit from dependencies 
* Remove pre-commit because it corrupting git hooks 
* Upgrade vuetify to get access to new features

Upgrade vuetify and remove precommit from dependencies 

---

src/components/ImageCards.vue

Add props to the add images component. 
[Trello card](https://trello.com/c/G6ktugY1/7-create-a-component-of-cards-to-be-used-for-showing-uploaded-images)
Unit testing, as well as manual testing to ensure cards were deleting properly.

Add images to create event slide

---

Jenkinsfile

[TO MASTER] Add fix for (weird branch build) error

---

src/components/CreateSlide.vue
src/components/Designer.vue
src/components/ImageCards.vue
src/router/index.js
src/store/modules/upload/index.js
test/unit/specs/CreateSlide.spec.js
test/unit/specs/ImageCards.spec.js

Moved the author slide functionality from Designer.vue to CreateSlide.vue and replaced Designer.vue with code for a wrapper. Also handled event emissions for ImageCards once the restructure took place so they would work properly.
[Trello card](https://trello.com/c/WiuqepF3/21-integrate-default-slide-template-with-authoring-view)
Allows the Designer.vue file to be used as a wrapper for the author view and the slide templates.
Tested that emissions are emitted properly when deleting an image from ImageCards.

restructure designer view

---

src/components/LandingPage/MainHeader.vue
src/components/LandingPage/MainNavDrawer.vue
test/e2e/nightwatch.conf.js

Fix issue #51 NavDrawer closes automatically 
Fix issue #51 NavDrawer closes automatically 
See Issue #51 
See Issue #51

[TO MASTER] Fix issue #51 NavDrawer closes automatically

---

src/components/Calendar.vue
test/unit/specs/Calendar.spec.js

Fix the bug of the old vision
Event is now returning a new slide const to fix the bug
Before: 
After:
Also changed the unit test based on the change

[Bug fix] Feature/calendar view

---

src/store/modules/slide/index.js

delete mutators which are now part of meta fields

---

src/components/Designer.vue
src/store/modules/slide/index.js
test/unit/specs/AddButton.spec.js

Add unit tests for default values, used sinon for testing click event.
Updating tests for thoroughness and to use best practices.

[TO MASTER] Feature/update add button unit tests

---

src/components/Designer.vue
src/store/modules/slide/index.js
test/unit/specs/FontStyle.spec.js

Organized unit tests for FontStyle.vue, and added tests for default values.
Update units for thoroughness and best practices

[TO MASTER] Feature/update font style unit tests

---

src/store/modules/slide/index.js
test/unit/specs/ImageCards.spec.js

Change ImageCards tests to use the store.
Add a few more tests to test with non-default data, and with empty array
Updating tests to test more and to test they work with the store
these are unit tests, run from file imageCards.spec.js

[TO MASTER] Feature/update image cards unit tests

---

src/components/Designer.vue
src/components/SlideCard.vue
src/components/Slides.vue
src/store/modules/slide/mutation-types.js
test/unit/specs/Slides.spec.js

The integration for the slide.vue

[TO MASTER] Feature/slides intergration
